jobs:
  - template: templates/linux-test-job.yml
    parameters:
      jobName: RunElectronUITestsOnLinux_1_CreateTypeSpecProject
      testScript: test:create
      displayName: Create TypeSpec Project
      artifactSuffix: create

  - template: templates/linux-test-job.yml
    parameters:
      jobName: RunElectronUITestsOnLinux_2_EmitTypeSpecProject
      testScript: test:emit
      displayName: Emit TypeSpec Project
      artifactSuffix: emit

  - template: templates/linux-test-job.yml
    parameters:
      jobName: RunElectronUITestsOnLinux_3_ImportTypeSpecProject
      testScript: test:import
      displayName: Import TypeSpec Project
      artifactSuffix: import

  - template: templates/linux-test-job.yml
    parameters:
      jobName: RunElectronUITestsOnLinux_4_PreviewTypeSpecProject
      testScript: test:preview
      displayName: Preview TypeSpec Project
      artifactSuffix: preview
