jobs:
  - template: templates/windows-test-job.yml
    parameters:
      jobName: RunWindowsTests_1_CreateTypespecProject
      testScript: test:create
      displayName: Run Create Test Cases
      artifactSuffix: create

  - template: templates/windows-test-job.yml
    parameters:
      jobName: RunWindowsTests_2_EmitTypespecProject
      testScript: test:emit
      displayName: Run Emit Test Cases
      artifactSuffix: emit
      installDotNet: true
      installMaven: true

  - template: templates/windows-test-job.yml
    parameters:
      jobName: RunWindowsTests_3_ImportTypespecProject
      testScript: test:import
      displayName: Run Import Test Cases
      artifactSuffix: import

  - template: templates/windows-test-job.yml
    parameters:
      jobName: RunWindowsTests_4_PreviewTypespecProject
      testScript: test:preview
      displayName: Run Preview Test Cases
      artifactSuffix: preview
